spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      #解决 Swagger 与 SpringBoot2.6.x 路径策略不一致的问题
      matching-strategy: ant_path_matcher
    # 让404错误抛出异常，需要同时设置spring.web.resources.add-mappings为false
    throw-exception-if-no-handler-found: true
  # 禁用静态资源的自动映射，如不禁用，不存在的url将被映射到/**，servlet不有机会抛出异常
  web:
    resources:
      add-mappings: false
# log 配置
logging:
  config: classpath:logging/logback-spring.xml

# swagger公共部分配置
swagger:
  package:
    base: cn.codeprobe.butin.controller
    portal: ${swagger.package.base}.portal
    admin: ${swagger.package.base}.admin
  version: v1.0