# tomcat配置
server:
  port: 8888
  servlet:
    context-path: /butin-api/dev
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 200
    connection-timeout: 5000ms
# Spring配置
spring:
  application:
    name: butin-api
  banner:
    charset: UTF-8
    location: banner/banner.txt
