## spring context
spring:
  profiles:
    active: dev   # dev: 开发环境， prod: 生产环境
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   #解决 Swagger 与 SpringBoot2.6.x 路径策略不一致的问题
    # 让404错误抛出异常，需要同时设置 spring.web.resources.add-mappings 为 false
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true    # 禁用静态资源的自动映射，如不禁用，不存在的url将被映射到/**，servlet没有机会抛出异常
  datasource:
    # 数据库连接池 druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      ## druid参数调优（可选）
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 测试连接
      testWhileIdle: true       # 是否在连接空闲一段时间后检测其可用性（默认true）
      testOnBorrow: false       # 是否在获得连接后检测其可用性（默认false）
      testOnReturn: false       # 是否在连接放回连接池后检测其可用性（默认false）
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      keep-alive: true              # 保持连接存在（默认false）
      # asyncInit是1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间
      asyncInit: true
      # 配置统计页面
      stat-view-servlet:
        enabled: true               # 是否开启（默认 false ）
        url-pattern: /druid/*       # 统计页面访问路径（默认）
        # 注：生产环境要打开用户名和密码的配置
        reset-enable: true          # 是否允许重置统计数据（默认 true ）
        allow: ""                   # 允许任意IP访问（默认 127.0.0.1 ）  #eny: 192.168.1.1 # 禁止访问的IP（优先级高于allow）
      # 配置监控统计拦截的 filters
      filters: "stat,wall,slf4j"
      # 配置Web应用、URI监控、Session监控
      web-stat-filter:
        enabled: true                 # 开启（默认 false）
        url-pattern: /*               # 监控的路径（默认）
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.woff2,/druid/*"   # 排除监控的路径或文件类型
        session-stat-enable: true         # 启用Session监控（默认）
        session-stat-max-count: 1000      # 最大统计的session数量
        profile-enable: true              # 监控单个url调用的sql列表

## log 配置
logging:
  config: classpath:logging/logback-spring.xml

## swagger公共部分配置
swagger:
  package:
    base: cn.codeprobe.butin.controller
    portal: ${swagger.package.base}.portal
    admin: ${swagger.package.base}.admin
    user: ${swagger.package.base}.user
  version: v1.0


## jwt
butin:
  jwt:
    header: "Authorization"     # token返回头部
    tokenPrefix: "Bearer "      # token前缀
    secret: "tobeabetterman"    # 加密密钥
    expireTime: 10              # token有效时间 (天)
    expireTimeCache: 15       # redis token有效时间 (天)

## mybatis配置
mybatis:
  type-aliases-package: cn.codeprobe.butin.model.po  # 参数类型的包别名设置  设置这个以后xml映射文件在 parameterType 的值就不用写成全路径名了
  mapper-locations: classpath:mapper/*.xml        # 指向映射xml文件目录
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
