# tomcat
server:
  port: 9999
  servlet:
    context-path: /butin-api
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 200
    connection-timeout: 5000ms

# spring
spring:
  banner:
    charset: UTF-8
    location: banner/banner.txt

# swagger 生产环境权限认证配置
swagger:
  # 开启生产环境屏蔽
  production: false
  basic:
    enable: true        # 开启Swagger的Basic认证功能,默认是false
    username: developer
    password: 123456